### ISSUE TITLE
Not compatibe with Django 3

### ISSUE THREAD

**Issue by Koed00** [torchbox/wagtail-experiments#21]
Because of this deprecated import, experiments is currently not compatible with Django 3. 
Even though Wagtail itself is.

```from django.utils.encoding import python_2_unicode_compatible```

**Comment by neowenshun** [comment]
Any updates regarding this issue?

**Comment by zerolab** [comment]
Hi both,

while not a complicated fix, we could use any help we can get, we will welcome a PR sorting this out. 

Thank you

**Comment by loveJesus** [comment]
God is good, so far replacing the import line in models.py this way allows the code to run.
`try:
    from django.utils.encoding import python_2_unicode_compatible
except ImportError:
    def python_2_unicode_compatible(aleluya):
        return aleluya`

**Comment by loveJesus** [comment]
God is good, another issue  is to change  `load staticfiles` to `load static` in line 2 of templates/experiments/report.html ; However this works only from Django 1.10 onwards. With my current knowledge of Django i do not see an easy way to detect the Django version and require one or the other conditionally. God guide us and bless you in Jesus name

**Comment by gasman** [comment]
Fixed in #33
