### ISSUE TITLE
TemplateSyntaxError 

### ISSUE THREAD

**Issue by 23rdPro** [torchbox/wagtail-experiments#27]
I have a TemplateSyntaxError at /admin/experiments/experiment/report/1/
'staticfiles' is not a registered tag library. Must be one of...

I checked the HTML file and saw: ```{% load staticfiles %}``` but lately, I think its ```{% load static %}```, ```django.contrib.staticfiles``` is installed.

**Comment by zerolab** [comment]
#26 should solve this. Can you give it a try?

**Comment by gasman** [comment]
Fixed in #33
