### ISSUE TITLE
0001_initial depends on migration from Wagtail's master branch

### ISSUE THREAD

**Issue by m1kola** [torchbox/wagtail-experiments#3]
[0001_initial](https://github.com/torchbox/wagtail-experiments/blob/e1ad75568b8e4d6569b94d3fb1170f9c8d99b0f0/experiments/migrations/0001_initial.py) depends on migration from Wagtail's master branch:

``` python
('wagtailcore', '0030_index_on_pagerevision_created_at'),
```

I see no reason to depend on this migration. It seems to me that we can specify earlier migration, so we will be able to support wider range of Wagtail versions.

**Comment by gasman** [comment]
Oops, forgot about this when building the 0.1 release...

Migration 0030 is part of Wagtail 1.7, so we're not requiring anyone to use an unstable version. I don't think there's an immediate need to support older versions, so I think we should save ourselves the extra maintenance effort and treat it as an encouragement for people to upgrade :-)
